name: Deploy via ftp
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest  # Altere para um runner Windows
    steps:
      - uses: actions/checkout@v2

      - name: FTP Deploy Locaweb
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "dist"  # Altere conforme a estrutura do seu projeto
